"""remove knowledge_base text column from business settings table

Revision ID: 5fd780d13bc2
Revises: 119e059a686b
Create Date: 2026-06-14 07:50:05.518880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd780d13bc2'
down_revision: Union[str, None] = '119e059a686b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_settings', 'knowledge_base')
    op.drop_index('ix_knowledge_chunks_embedding_ivfflat', table_name='knowledge_chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_chunks_embedding_ivfflat', 'knowledge_chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('business_settings', sa.Column('knowledge_base', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
